spring:
  kafka:
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "com.app.kafka.message"
server:
  port: 0
chunk.max-size: 1048576
audio:
  dir: audio
  max-size: 37748736
image:
  dir: images
  default: default_image.png
  max-size: 1048576 